{% set name = "simpeg-drivers" %}
{% set version = "0.1.1" %}
{% set python_min = 3.10 %}
{% set python_max = 3.11 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MiraGeoscience/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 4a23457f414da43b67324a9d11dfcff1d18ae33fc2f7bf2e22af427d0ed4750b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 
  number: 1

requirements:
  host:
    - pip
    - python >={{ python_min }},<{{ python_max }}
    - poetry-core >=1.0.0
  run:
    - python >={{ python_min }},<{{ python_max }}
    - dask-core 2022.10.*
    - discretize >=0.10.0,<0.11.0
    - distributed 2022.10.*
    - geoh5py >=0.9.0,<0.10.0
    - geoapps-utils >=0.3.0,<0.4.0
    - mira-simpeg >=0.19.0.8,<0.19.0.9
    - numpy >=1.23.5,<1.24.0
    - param-sweeps >=0.1.8,<0.1.9
    - octree-creation-app >=0.1.1,<0.2.0
    - scipy >=1.10.0,<1.11.0
    - zarr >=2.14.2,<2.15.0
    - tbb 2021.12.*
    - python-tzdata 2023.4.*
  run_constrained:
    - pillow >=10.3.0,<10.4.0
    - fsspec 2022.*
    - geoana >=0.4.0,<0.5.0
    - __glibc >=2.17
    - h5py >=3.2.1,<4.0.0
    - matplotlib-base >=3.7.1,<3.8.0
    - mkl 2022.1.*
    - pandas >=2.2.1,<2.3.0
    - pydantic >=2.5.2,<2.6.0
    - pydiso >=0.0.3,<0.1.0
    - pymatsolver >=0.2.0,<0.3.0
    - scikit-learn >=1.4.0,<1.5.0
    - tqdm >=4.66.1,<5.0.0

test:
  imports:
    - simpeg_drivers
  commands:
    - pytest tests/version_test.py
    - pip list
  requires:
    - python >={{ python_min }},<{{ python_max }}
    - pip
    - pytest
    - tomli
  source_files:
    - tests/version_test.py
    - pyproject.toml
    - README.rst

about:
  home: https://www.mirageoscience.com/mining-industry-software/python-integration/
  summary: 'Application to run SimPEG inversions with geoh5 files from Geoscience Analyst.'
  license: MIT
  license_file:
    - LICENSE
  doc_url: https://mirageoscience-simpeg-drivers.readthedocs-hosted.com
  dev_url: https://github.com/MiraGeoscience/simpeg-drivers

extra:
  recipe-maintainers:
    - SophieCurinier
    - sebhmg
