schema_version: 1

context:
  name: simpeg-drivers
  version: "0.4.0"
  python_min: '3.10'
  python_max: '3.12'
  module_name: ${{ name|lower|replace("-", "_") }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/MiraGeoscience/${{ name }}/archive/v${{ version }}.zip
  sha256: c82f4e31575d0dc5f95b49be0b4e23802ca196310384a007db1a33fe3358b082

build:
  number: 0
  noarch: python
  script:
    - export POETRY_DYNAMIC_VERSIONING_BYPASS=${{ version }}
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python 3.10.*
    - poetry-core >=1.8.0
    - poetry-dynamic-versioning >=1.9, 1.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }},<${{ python_max }}
    # Mira packages
    - geoapps-utils >=0.6.0, 0.6.*
    - geoh5py >=0.12.0, 0.12.*
    - grid-apps >=0.1.0, 0.1.*
    - mira-simpeg >=0.23.0.2, 0.23.0.*
    # direct dependencies
    - dask-core >=2025.3, 2025.3.*
    - discretize >=0.11.0, 0.11.*
    - distributed >=2025.3, 2025.3.*
    - numpy >=1.26.0, 1.26.*
    - pydantic 2.11.*
    - pydiso >=0.1.0, 0.1.*
    - python-mumps >=0.0.3, 0.0.3.*
    - rtree >=1.2.0, 1.2.*
    - scikit-learn >=1.6.0, 1.6.*
    - scipy >=1.14.0, 1.14.*
    - tqdm >=4.66.1, 4.66.*
    - trimesh >=4.1.3, 4.1.*
    # constrain version for some indirect dependencies from SimPEG
    - geoana >=0.7.0, 0.7.*
    - matplotlib-base >=3.8.4, 3.8.*
    - pymatsolver >=0.3.0, 0.3.*
    - zarr >=2.14.2, 2.14.*
  run_constraints:
    - __glibc >=2.17
    - bokeh >=3.6.0, 3.6.*
    - fsspec >=2022.0

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - simpeg_drivers
        - dask
        - distributed
        - geoh5py
        - simpeg
      pip_check: true
      
  - script:
      - pytest --ignore=tests/version_test.py
    requirements:
      run:
        - pytest
    files:
      source:
        - tests/

  - package_contents:
      files:
        - site-packages/${{ module_name }}/_version.py

about:
  summary: Application to run SimPEG inversions with geoh5 files from Geoscience Analyst.
  license: MIT
  license_file: LICENSE
  homepage: https://www.mirageoscience.com/mining-industry-software/python-integration/
  repository: https://github.com/MiraGeoscience/simpeg-drivers
  documentation: https://mirageoscience-simpeg-drivers.readthedocs-hosted.com/

extra:
  recipe-maintainers:
    - conda-forge/geoh5py
